### ISSUE TITLE
Api idWilayah gagal

### ISSUE THREAD

**Issue by farchanakbar** [ibnux/BMKG-importer#2]
halo mas, api untuk liat perkiraan cuaca berdasarkan id wilayahnya gabisa ya mas? saya coba cuman list kosong hasilnya

**Comment by ibnux** [comment]
sampai sekarang data di BMKG tidak ada update sejak Juli

https://data.bmkg.go.id/prakiraan-cuaca/

**Comment by farchanakbar** [comment]
Ooh baik mas, brarti nanti ketika sudah update dari bmkg bakalan bisa ya mas di akses api nya

**Comment by ibnux** [comment]
Iya, karena scriptnya jalan tiap 2 jam sekali
